source 'https://rubygems.org'

gem 'rory'
gem 'thin'
gem 'sequel'
gem 'pg'
gem 'database_operations', :git => 'git@github.com:projectdx/database_operations.git'


group :development, :test do
  gem 'rake'
  gem 'byebug'
end
