default: &default
  # Add api token here
  token: 'test-token'

test:
  <<: *default

development:
  <<: *default

alpha:
  <<: *default

qa:
  <<: *default

beta:
  <<: *default

production:
  <<: *default
